DhairyaBahl/React-Messenger-App

- Contributing.md
- src/Messages.css
> Added Padding within messages

- Contributors.md
- src/App.css
- src/App.js
- src/Messages.css
- src/index.css
Fixes #9 
https://user-images.githubusercontent.com/2000917/105260355-a8f96400-5b5b-11eb-953b-969748f6917b.mp4
> Enhancing dark mode experience

- Contributors.md
- public/index.html
- src/App.js
- src/Messages.css
- src/Messages.js
#18 fixed overFlowing text & #16 added timeStamp
fixed some small bugs too
> fixed overFlowing text & added timeStamp

- Contributors.md
- src/Messages.css
> Added responsive width of message box.

- src/App.css
The background image of the app is being fixed, now it doesn't scroll while scrolling messages
> fix: background image scrolling fixed

- Contributors.md
Added a contributor in Contributors.md
> updated Contributors.md

- src/Messages.css
I have made changes in the Messages.css file. 
Please merge this PR.
Thanks
Himika Mishra
> issue #61: successfully handled

- src/Messages.js
> solved error

- Contributors.md
- README.md
> Added Contributor

- .gitignore
- src/App.css
- src/Messages.js
> made header section responsive

- package-lock.json
- src/Messages.css
> Remove text-overflow

- src/Messages.css
@DhairyaBahl Please now merge it . 
The changes are now successfully made .
The changes were -
the textboxes were made small and the text font size reduced. 
As we have discussed.
Thanks Himika Mishra
> issue 81 resolved successfully

- src/Messages.css
@DhairyaBahl Please now merge it . 
The changes are now successfully made .
The changes were -
the colors of the textboxes changed as I added the gloss effect. 
Now it is trendy and new.
As discussed earlier.
Thanks Himika Mishra
> issue #82 successfully resolved

- src/Messages.css
Hi @DhairyaBahl ,
Kindly merge this PR.
The changes has been successfully done in the messages.css file. 
The changes are as follows-
I added the opposite colors in the shadow of the textboxes.
So now they are looking trendy and different and different from many apps.
Thanks
Himika Mishra
> Issue#68 successfully resolved.

- src/Messages.css
Hi,
As discussed and according to current merged repository, I have resolved this issue of text overflow.
Kindly check it as I have uploaded the previous and new(changed) ss.
Please @DhairyaBahl @abhijeet007rocks8 and merge this PR asap.
Thanks 
Himika Mishra
> issue #90 resolved succesfully

- src/App.js
- src/WelcomeDialogBox.js
> Created a dialog box for username input

- src/Messages.css
Closes #96 
Screenshot:
Without hover
On hover
> Add Read More Improvements

- src/App.js
Closes #99 
Added a print function which disables empty strings to send
> Disabled empty messages

- src/App.js
Fixes: #103 
Someone removed the `FormControl`, `but` and `SendIcon` from the repo, so I added them in a proper way.
> Fixed the code by adding some deleted component

- src/App.css
- src/App.js
Closes #97
A preview:
The animation in the gif is a bit choppy but it works smoothly in the website.
> Added loading component

- src/App.css
- src/App.js
> removed input box! fixes #111

- src/App.css
- src/App.js
Changed Input Font-size and padding to make the input box visually appealing. 
fixes #110
> Changed Input Font-size and padding

- src/App.js
Fixed issue #162
Message can now be send by pressing enter key.
> Message sent by pressing enter key

- src/App.js
- src/components/contactForm/contactForm.css
- src/components/contactForm/contactForm.js
Partial fix of #132
Contact form Frontend made. Fully responsive, clean UI, with simple validation, name, subject, email address and text area fields, submit button.
screenshots:
> Contactform frontend

- Contributors.md
- src/App.js
This PR will close issue #170,
Before changes
[Link to Gif](https://drive.google.com/file/d/1LMp2m-F69GsLeEZOu6CfZKqjjdSE5ljE/view?usp=sharing)
After changes
[Link to Gif](https://drive.google.com/file/d/144uqUL7OvsYZQKefe-suPvX0Z03eKH_J/view?usp=sharing)
> fix: fixed issue #170

- src/App.css
- src/App.js
Spend some time to take the correct UI which perfectly compliments the UI of the website. 
Fixes #167
> New logo UI

- package-lock.json
- package.json
- src/App.js
- src/components/contactForm/contactForm.css
- src/components/contactForm/contactForm.js
Partial fix of #132
Contact form Frontend made. Fully responsive, clean UI, with simple validation, name, subject, email address and text area fields, submit button.
screenshots:  
sending HTTP request using email js:  
mail received:
> Contactform backend

- src/components/messages/Messages.js
Added time and date for messages.
Fixed #180
> Added date and time for messgaes

- src/components/about-us/Abouts.css
Closes Issue #181 
I have added the floating animation in the logo .
Demo:
> Floating animation added in logo in about us.

- .github/workflows/add_label.yml
- .github/workflows/pr_label.yml
when the contributor makes  a PR gssoc21 label is added .
fix#116 resolve#116
> auto-label action  added

- package-lock.json
- src/components/messages/Messages.js
Fixed issue #192 
Messages are loading now.
> Fixed issue: Messages not loading

- src/App.css
- src/App.js
Fixes issue: #182 
Changes made:-
- Dark theme is now working for the navbar
- size of logo and navbar reduced
- color of buttons and icons changed to the theme color
> Navbar ui modified

- src/components/footer/footer.css
- src/components/footer/footer.js
> Size reduced of footer on about us page.

- src/components/contactForm/contactForm.css
- src/components/contactForm/contactForm.js
Fixes issue: #188 
I have made the contact us form more attractive and user-friendly.
> Contact us form modified.

- src/components/footer/footer.js
> Fixed the twitter link of footer

- src/components/contactForm/contactForm.js
> Added email validation in contact-us form

- src/App.js
> Fixed Emoji Insertion Bug

- src/App.js
- src/components/contactForm/contactForm.css
- src/components/contactForm/contactForm.js
> Theme change is now working for contact us form.

- package-lock.json
- package.json
- src/App.js
Fixes #202: Now the user can speak by pressing the mic button instead of typing the message, the speech will be converted to text and set as input in the message field
> Added Speech to text input.

- src/App.css
- src/App.js
The navmenu theme is working properly now.
Fixes #211
> Fixed navmenu theme in mobile view.

- src/App.css
> enhance the styling of audio button

- src/components/faq/faq.js
Since we are repeating the same component, I have made the data into array of objects and mapped over it! As js increases so do loading time,  so this will be quite helpful.
part of #132
> changed FAQ data into array of objects and mapped over it

- src/components/Landingpage/LandingPage.css
- src/components/Landingpage/LandingPage.jsx
FIxes issue: #219 
Now there is no issue with button.
This issue occuered due to using the `button` tag directly for styling
> Button styling issue fixed

- src/App.js
> Added Scroll to bottom button

- .eslintrc.js
- package-lock.json
- package.json
Fixes issue #237 I have set up .eslint.json file and enhanced package.json file and set up the eslint and prettier code in project ESLint is the code quality linter, Prettier is the code formatting tool while EditorConfig will provide everyone with the right editor configuration.
> set up eslint and prettier code 

- src/App.js
- src/components/Featurespage/FeaturesPage.css
- src/components/Featurespage/FeaturesPage.jsx
Fixes issue: #242 
Feature page now have dark theme also.
> Added dark theme support for feature page

- src/App.js
- src/components/footer/footer.css
- src/components/footer/footer.js
Both light and dark theme are working now for the footer.
> Footer theme switch fixed.

- src/components/faq/faq.js
handled dropdown of cards by creating and using a custom function. Searched online and learnt this method to automatically close a dropdown when another dropdown is opened.
video to show this awesome effect:
https://drive.google.com/file/d/1nG9zXpWD52HlZnI8pPebXud6cDqIfoPN/view?usp=sharing
> handled dropdown of cards by using custom function

- .eslintrc.js
- src/components/contactForm/contactForm.js
Fixed issue: #252 
In the eslint.js there were some ruler which were set to error, I have changed them to warning, now they will throw warning instead of throwing compilation error. They were causing the compilation error.
> fixed the rules of eslint setup

- src/App.js
- src/components/faq/faq.css
- src/components/faq/faq.js
> Added dark theme for FAQ section.

- src/App.css
- src/components/Featurespage/FeaturesPage.css
Fixes: #259 
Now the page is responsive till screen sizes of 300px
| Before | After | 
|---------|-------|
> Fixed Responsiveness in Features Page

- src/App.js
- src/components/Landingpage/LandingPage.css
- src/components/Landingpage/LandingPage.jsx
> Landing page in both light and dark mode.

- src/components/messages/Messages.css
> made sender's name visible

- .gitignore
- src/firebase.js
Fix issue : #229 
I have added all the API keys in `.env` file and included that in `.gitignore` file
> Hiding api keys

- package-lock.json
- src/App.css
- src/App.js
> the dropdown arrow key(scroll to bottom) added to the bottom right corner

- src/App.js
> Added Space between Input Area and Latest Message

- src/App.js
> adding dark theme to footer of feature page

- src/App.js
> Dark theme to footer of login page

- README.md
Improved dependencies section and corrected grammar.
> Issue #305

- src/components/about-us/About.js
(Screenshots attached in linked issue)
> Fixed mis-ordered text on About page

- src/App.css
- src/App.js
- src/components/footer/footer.js
> Scroll button

- src/components/footer/footer.js
> adding dynamic year to footer

- src/App.js
- src/components/footer/footer.js
> Toggle icon

- src/App.js
solves #307 
now every page is loaded in their specific route alone!
> Messages bug solved!

- src/App.css
> Content of the message input field aligned to center

- src/components/Featurespage/FeaturesPage.css
fixes #283 
html tag was dirently modified here, resulting in problem everywhere
> About us text size fixed

- src/App.css
Fixes #284 
HTML tag was directly modified in the features page, resulting in problems in other places
> navbar lightmode size fixed

- src/components/footer/footer.css
> footer bug fixed

- src/components/messages/Messages.css
> timestamp colour changed

- src/components/Featurespage/FeaturesPage.jsx
fixes #286 , both dark and light mode!
> added secondary texts, both dark and light mode

- src/App.js
- src/components/Landingpage/LandingPage.css
- src/components/Landingpage/LandingPage.jsx
> Landing page contents aligned.

- src/App.js
- src/components/login/login.css
- src/components/login/login.jsx
> Added dark theme for login form.

- src/App.css
- src/App.js
> Onscreen keyboard in dark issue fixed.

- src/components/messages/Messages.css
> Font size fixed of message box.

- src/App.css
> Enhanced styling of onscreen_keyboard icon.

- src/App.js
- src/components/Landingpage/LandingPage.css
- src/components/Landingpage/LandingPage.jsx
> Added dark theme in footer of landing page.

- src/App.css
- src/App.js
> Postion of emoji picker fixed in dark mode.

- src/App.js
> store messages in local storage

- src/components/faq/faq.css
- src/components/faq/faq.js
> custom dark and light mode background

- src/components/footer/footer.css
Added hover style to footer logo.
FIXES: #398
> Hover style to footer logo

- src/components/footer/footer.css
Added shadow to the footer.
FIXES : #397
> added shadow to footer

- src/components/login/login.jsx
- src/components/signup/signup.jsx
I've added route to the login and signup page when clicked on "create your account" and "already have an account".
Fixes: #399
> Added route to pages

- src/components/faq/faq.js
>  Compilation error fixed.

- src/components/footer/footer.css
- src/components/footer/footer.js
> fixed the font size of icons in footer

- src/components/footer/footer.css
- src/components/footer/footer.js
> Increased footer text in mobile

- src/App.js
- src/components/forgetpass/forget.jsx
- src/components/resetpass/reset.css
- src/components/resetpass/reset.jsx
I've added the frontend part of reset password page. Although this page can be visited when someone uses the forgot password page to send an email to reset the password. But as I don't have much knowledge of the backend here, so I created the front end part of reset password page. 
- Currently this page can be visited when you click on the submit button on "Forgot Password Page" .
Fixes: #416
> Added reset password page

- src/App.js
- src/components/login/login.css
- src/components/login/login.jsx
- src/components/signup/signup.css
- src/components/signup/signup.jsx
> Fixed Dark Mode of Login & Signup Page

- src/components/Featurespage/FeaturesPage.css
> Features page issue fixed.

- src/components/Featurespage/FeaturesPage.css
- src/components/Featurespage/FeaturesPage.jsx
> Added floating animation to feature page.

- src/components/Landingpage/LandingPage.css
- src/components/Landingpage/LandingPage.jsx
> Size of landing page fixed.

- src/components/forgetpass/forget.css
- src/components/login/login.css
- src/components/resetpass/reset.css
- src/components/signup/signup.css
> Improved UI of Submit Button

- src/components/messages/Messages.css
> increased the font size of messages in mobile view

- src/components/contactForm/contactForm.css
- src/components/faq/faq.js
- src/components/messages/Messages.css
Fixed issue #430 
Before faq page were hidden by contact us form, I have fixed it
> Made faq component visible

- src/components/contactForm/contactForm.css
- src/components/faq/faq.js
- src/components/messages/Messages.css
> Contact us form

- package-lock.json
- package.json
- src/App.css
- src/App.js
> Feature copy to clipboard added.

- src/components/Landingpage/LandingPage.css
> Floating animation added in landing page.

- Messenger-Native-App/dark-light-theme/constants.js
- Messenger-Native-App/dark-light-theme/index.js
- Messenger-Native-App/dark-light-theme/propTypes.js
- Messenger-Native-App/dark-light-theme/themes.js
> light and dark theme UI added for native app

- src/App.js
>  Compilation Error fixed

- src/components/contactForm/contactForm.js
> Feature auto complete added in contact us form.

- src/components/faq/faq.css
- src/components/faq/faq.js
> custom background for individual faqs

- src/App.css
> small screen navbar

- src/App.css
> Navbar dropdown

- src/App.css
> Inputbox dark mode

- src/App.css
- src/components/login/login.css
> Login responsive

- src/App.css
- src/components/about-us/Abouts.css
- src/components/login/login.css
> Aboutus text mobile

- react-mentions/demo/src/examples/BottomGuard.js
- react-mentions/demo/src/index.html
- react-mentions/demo/src/index.js
- react-mentions/src/Mention.js
- react-mentions/src/MentionInput.js
> tagging previous message and react-mentions

- additional-themes/package-lock.json
- additional-themes/package.json
- additional-themes/pages/_app.js
- additional-themes/pages/_document.js
- additional-themes/pages/colourTheme.js
- additional-themes/pages/index.js
> additional multicolour themes added

- src/App.js
> Compilation error fixed

- src/components/Landingpage/LandingPage.css
> Landing page mobile image removed for smaller devices

- src/components/footer/footer.css
- src/components/footer/footer.js
> Hover to footer logo

- src/components/footer/footer.css
> Aligned footer text

- src/components/Featurespage/FeaturesPage.css
- src/components/Featurespage/FeaturesPage.jsx
- src/components/Landingpage/LandingPage.css
- src/components/Landingpage/LandingPage.jsx
> Changed color for dark text

- src/components/faq/faq.css
- src/components/faq/faq.js
> increase the size of faq's in mobile view

- src/components/preloader/preloader.jsx
- src/components/preloader/styles.css
fixes #309
@abhijeet007rocks8 i have made the preloader but the problem is someone has deleted the code splitting that I implemented a week ago, now I have do it all over again so that you can see the changes in performance! Pleased merge this now, I will make code splitting issue again
> preloader made

- src/App.css
> Fixed visibility of text in dark mode

- src/components/Landingpage/LandingPage.css
> Styled Enter chat button

- src/components/messages/Messages.css
> updated messages color scheme

- src/App.css
> increased the size of navbar in dark theme

- src/components/signup/signup.css
- src/components/signup/signup.jsx
> email field issue in dark mode fixed

- src/App.css
> mobile change theme button

- flickrapp/app/components/app.jsx
> mobile support application for the app

- src/App.css
- src/components/login/login.jsx
- src/components/signup/signup.jsx
> Fixed Overlapping of Scroll to Bottom Button with Input Field

- src/App.css
- src/App.js
Fixes: #578 
Added styles in nav-menu media query, removed excess class toggle-button.
> Fixed Navigation menu

- markup_patterns/index.js
- markup_patterns/provideExamplevalue.js
> multiple markup patterns

- UI-styling/codestyleconfig.xml
- styles-header/index.js
- styles-header/styles.js
> UI improvement done 

- styles-header/index.js
- styles-header/styles.js
> added new styles header to app

- src/App.css
> Load older messages button modified

- src/App.css
Fixes: #530 
I have set the height of logo to 50px for all views.
> Fixed logo size

- src/App.css
FIXES: #572 
Removed translate property. 
Added right = 15px;
> Fixed nav icon

- src/App.css
> Fixed navigation gap

- src/components/about-us/About.js
- src/components/about-us/Abouts.css
Some material ui class was overflowing, changed font to rems, padding to ems.
FIXES: #569
> Fixed About us on mobile.

- src/App.css
- src/App.js
> Added status copied after the text is copied.

- src/App.css
> Size of message input field in dark mode fixed.

- jwt_authentication/auth.js
- jwt_authentication/frontauth.js
> added jwt authentication feature and token in app

- src/App.css
- src/App.js
> dark theme added for load more message button

- src/components/sidebar/index.html
- src/components/sidebar/sidebar.css
- src/components/sidebar/sidebar.js
> navbar changed to sidebar or navigation drawer

- src/components/Landingpage/LandingPage.css
- src/components/forgetpass/forget.css
> Fixed Responsiveness of Forgot password page

- src/routes/api.js
> added private routes and sending requests to API

- src/components/signup/signup.css
- src/components/signup/signup.jsx
> Animation added in sign up .

- src/components/models/schema.js
> added models and schema components

- src/components/resetpass/reset.css
> animation added in reset prassword page.

- src/components/forgetpass/forget.css
> animation added in forget password

- src/components/signup/signup.css
> error fixed in email field

- SignIn-Signup/signinform.js
> added styles and tokens to sign-in form

- src/components/login/login.css
> Animation added in login page

- SignIn-Signup/signupform.js
> added styles and tokens to signup form

- users/users.js
- users/users.test.js
> added users to chat app

- src/App.js
- src/components/signup/signup.jsx
> Add logout feature

- users/user-list.js
- users/user-repo.js
> rendering users list and users repo list

- src/App.js
> selective rendering of navbar items

- src/components/contactForm/contactForm.css
- src/components/contactForm/contactForm.js
- src/components/signup/signup.jsx
> Fixed Responsiveness Of Contact Us

- package.json
- src/components/login/login.jsx
- src/components/signup/signup.jsx
> Content of login page aligned

- users/modals/index.js
> created error and loading modal file in react

- src/components/signup/signup.jsx
> fixing compilation error

- users/wallpaper-app-container.js
- users/wallpaper.js
> react wallpapers added for users

- src/components/elements/dropdown/dropdown.js
- src/components/elements/dropdown/dropdown.scss
- src/components/elements/dropdown/dropdownbutton.js
- src/components/elements/dropdown/dropdowndivider.js
> fixing dropdown position element

- src/components/toggle/tab/tab.js
- src/components/toggle/tab/tabButton.js
- src/components/toggle/tab/tabContent.js
> adding tab toggle component

- src/components/elements/box-icon/icon.js
- src/components/elements/box-icon/icon.scss
- src/components/elements/box-icon/icon.spec.js
> added content box-icon

- chatbot/chatbot.js
- chatbot/structjson.js
> creating a chatbot and fixing token encoding

- improve-login/ErrorMessage.js
- improve-login/login.js
> improved and fixed login component

- src/components/messageloading/Content.js
- src/components/messageloading/Loading.js
- src/components/messageloading/connectBackend.js
> fixed the messages loading for selected room

- src/components/back-button/MessagesPanel.js
- src/components/back-button/WriteMessage.js
> improved and enhanced the back-button

- improve-layout/Footer.js
- improve-layout/Header.js
- improve-layout/Logout.js
- improve-layout/title.js
> enhanced and improved layout

- improve-layout/title.js
> added title feature in layout

- improve-layout/logout.js
> added logout feature in layout component

- improve-layout/user-greeting.js
> added user greeting feature

- helpers/helpers.js
> added object id instance in helpers

- src/components/messages/messagelist.js
> added messages list

- users/users-menu.js
> added users list

- flexbox/flexbox-react-test.jsx
- flexbox/flexbox.jsx
> added flexbox to design frontend of react app

- src/components/rooms/RoomInfo.js
- src/components/rooms/RoomPanel.js
> enhance online mark in chat-room

- users/searchuser.js
> added search user feature in users

- users/usermenu.js
> added user menu component

- users/userform.js
> added user form feature in app

- src/components/models/messages.js
> creating the messages model component

- src/App.css
> Fixed nav toggle

- src/App.css
> Aligned nav toggle

- src/App.css
> Load button

- src/components/Featurespage/FeaturesPage.css
> made features page responsive

- src/components/signup/signup.jsx
> Fixed Multiple Signup Buttons & Aligned Items

- src/components/login/login.jsx
> Fixed Multiple Forgot Password Buttons

- src/components/forgetpass/forget.css
> issue fixed of email input in forgot page

- src/components/forgetpass/forget.jsx
> Added on scroll animation in forgot password page.

- package-lock.json
- package.json
- src/App.js
> feature added to share geolocation

- package-lock.json
- package.json
- src/components/signup/signup.css
- src/components/signup/signup.jsx
> feature added to login with github

- src/components/Featurespage/FeaturesPage.css
> Enhanced Features mobile view

- src/App.css
> Positioned scroll button

- src/components/Landingpage/LandingPage.css
> Fixed landing text

- src/components/contactForm/contactForm.css
- src/components/contactForm/contactForm.js
> Fixed contact form

- src/components/about-us/Abouts.css
> fixed font size for about text

- package-lock.json
- package.json
- src/App.js
> feature added to share gif

- src/App.css
- src/App.js
- src/WelcomeDialogBox.js
>  Dark theme feature added in  welcome dialoge  box.

- users/userbar.js
> added user bar component in app

- fonts/index.test.tsx
> added fonts in react app

- src/authentication/authen.js
> adding authenticated user

- src/components/conversation/conversation.js
> creating conversation feature header footer

- src/components/conversation/conversationlist.js
> conversation list added

- src/input/searchinput.js
> added search input file

- text-message/message.js
> added text message file with error

- subscriptions/text.js
- subscriptions/user.js
> added subscription on text

- authorization/auth.js
- subscriptions/user.js
> Added Authorization for subscriptions

- src/document/document.js
- subscriptions/user.js
> Added Document page

- emoji-react/emoji.js
- subscriptions/user.js
> Added random Emoji file

- middlewares/permissions.js
- subscriptions/user.js
> Initializing Middlewares

- Authpayload/authpayload.js
- subscriptions/user.js
> Adding Authpayload

- query/query.js
- subscriptions/user.js
> Adding Query file

- mutations/mutation.js
- subscriptions/user.js
> Mutation file added

- profile-view/app.js
- subscriptions/user.js
> Full view profile added
